## @name local-test
### @name api
curl -X GET http://localhost:8000/api

### @name get-auth-token
curl -X POST  http://localhost:8000/api/auth/token

### @name verify-token
curl -X GET http://localhost:8000/api/auth/verify 
-H "x-antchain-token: eyJhbGciOiJub25lIn0.eyJzdWIiOiI3MWYzN2QwOS1mMDA5LTQ4NmMtOWFhYy0xZWJjNGJmNjU1NjMiLCJpYXQiOjE3NTA3NTU2MjIsImV4cCI6MTc1MDc1NzQyMiwiZXh0ZW5kIjoie1wiYWNjZXNzSWRcIjpcIjcxZjM3ZDA5LWYwMDktNDg2Yy05YWFjLTFlYmM0YmY2NTU2M1wiLFwiZmxhZ1wiOjAsXCJ0ZW5hbnRJZFwiOlwiNzFmMzdkMDktZjAwOS00ODZjLTlhYWMtMWViYzRiZjY1NTYzXCJ9In0."

### @name deposit-data
curl -X POST http://localhost:8000/api/node/data/store 
-d '{"data": "Hello, World!"}'

### @name query-data
curl -X POST http://localhost:8000/api/node/data/query 
-d '{"dataId": "2b50c37a1bcd977d21c928477bdfa9e8163c50f927e6d3431488fc0067fab210"}'

### @name parse-data
curl -X POST http://localhost:8000/api/node/data/parse 
-d '{
  "success": true,
  "data": "{\"blockNumber\":220718,\"hash\":\"2b50c37a1bcd977d21c928477bdfa9e8163c50f927e6d3431488fc0067fab210\",\"transactionDO\":{\"data\":\"IkhlbGxvLCBXb3JsZCEi\",\"timestamp\":1750814699065,\"txType\":\"TX_DEPOSIT_DATA\"}}"
}'